# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evaluateGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtGui import QPixmap
import FantasyCricket.FantasyCricket.BattingBowlingPoints
import sqlite3
import math


class Ui_Form(object):
    def __init__(self):
        self.pointsList = []
        self.playersList = []
        self.total = 0
        
    def renderTeam_Match(self):
        sqlC = self.databaseConn()
        sqlC.execute("SELECT DISTINCT Tname FROM Teams")
        teamNames = sqlC.fetchall()
        for i in teamNames:
            self.CB1.addItem(i[0])

        sqlC.execute("SELECT DISTINCT Matches FROM Match")
        matches = sqlC.fetchall()
        for i in matches:
            self.CB2.addItem(i[0])
        
    def databaseConn(self):
        conn = sqlite3.connect("C:\\Users\\gpavi\\Desktop\\FantasyCricketGame\\Database\\Fantasy Cricket.db")
        sqlcursor= conn.cursor()
        return sqlcursor
    
    def msgbox(self,title,message,icon):
        msg= QMessageBox()
        msg.setStyleSheet("Font-size:15px; font-weight: bold;")
        msg.setWindowTitle(title)
        msg.setIconPixmap(QPixmap(icon).scaled(60,60))
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msg.setText(message)
        msg.exec_()
        
    def teamList(self):
        selectedTeam = self.CB1.currentText()
        sqlC = self.databaseConn()
        sqlC.execute("SELECT Players FROM Teams WHERE Tname = ?",(selectedTeam,))
        players = sqlC.fetchall()
        self.Player_listWidget.clear()
        for i in players:
            self.playersList.append(i[0])
            self.Player_listWidget.addItem(i[0])

    def cal(self):
        self.points = 0
        self.total = 0
        self.players = []
        self.pointsList = []
        self.Points_listWidget.clear()

        self.lineEdit.setText(str(self.total))
        team = self.CB1.currentText()
        match = self.CB2.currentText()
        sqlC = self.databaseConn()
        for i in range(self.Player_listWidget.count()):
            self.players.append(self.Player_listWidget.item(i).text())
        #print(players)
        for player in self.players:
            sqlC.execute("SELECT * FROM Match WHERE Players = ?",(player,))
            score = sqlC.fetchall()
            #print(score)
            if score[0][12] == match:
                self.points = FantasyCricket.FantasyCricket.BattingBowlingPoints.batting(score)
                
            self.Points_listWidget.addItem(str(self.points))
            self.pointsList.append(self.points)
            #print("points",self.pointsList)
            
        for i in self.pointsList:
            self.total += i
        self.lineEdit.setText(str(self.total))
        
            
    def points(self):
        if "----SELECT TEAM----" == self.CB1.currentText() and "----SELECT MATCH----" == self.CB2.currentText():
            self.msgbox("Warning","Select a Team and Match to evaluate","Images of Fantasy Cricket\\TM.png")
        elif "----SELECT TEAM----" == self.CB1.currentText() and "----SELECT MATCH----" != self.CB2.currentText():
            self.msgbox("Warning","Select a Team to evaluate","Images of Fantasy Cricket\\team4.jpg")
        elif "----SELECT TEAM----" != self.CB1.currentText() and "----SELECT MATCH----" == self.CB2.currentText():
            self.msgbox("Warning","Select a Match to evaluate","Images of Fantasy Cricket\\match.jpg")   
        else:
            self.cal()
            
                    
    def setupUi(self, Form):
        conn = sqlite3.connect("C:\\Users\\gpavi\\Desktop\\FantasyCricketGame\\Database\\Fantasy Cricket.db")
        sqlC= conn.cursor()
        Form.setObjectName("Form")
        Form.resize(538, 523)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CB1 = QtWidgets.QComboBox(Form)
        self.CB1.setObjectName("CB1")
        self.CB1.addItem("")
        self.CB1.setItemText(0, "---Select Team---")
        
        self.horizontalLayout_2.addWidget(self.CB1)
    
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.CB2 = QtWidgets.QComboBox(Form)
        self.CB2.setObjectName("CB2")
        self.CB2.setItemText(0, "---Select Match---")
        self.CB2.addItem("")
        
        self.horizontalLayout_2.addWidget(self.CB2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Label_Players = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Players.setFont(font)
        self.Label_Players.setObjectName("Label_Players")
        self.horizontalLayout_3.addWidget(self.Label_Players)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.Label_Points = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Points.setFont(font)
        self.Label_Points.setObjectName("Label_Points")
        self.horizontalLayout_3.addWidget(self.Label_Points)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        
        self.Player_listWidget = QtWidgets.QListWidget(Form)
        self.Player_listWidget.setObjectName("Player_listWidget")
        self.horizontalLayout_4.addWidget(self.Player_listWidget)
        
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        
        self.Points_listWidget = QtWidgets.QListWidget(Form)
        self.Points_listWidget.setObjectName("Points_listWidget")
        self.horizontalLayout_4.addWidget(self.Points_listWidget)
        
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Calculate_btn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Calculate_btn.setFont(font)
        self.Calculate_btn.setObjectName("Calculate_btn")
        self.horizontalLayout_5.addWidget(self.Calculate_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        
        self.renderTeam_Match()
        self.Calculate_btn.clicked.connect(self.points)
    
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.CB1.activated.connect(self.teamList)
        #self.CB2.activated.connect(self.points)
 

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "EVALUATE TEAM"))
        self.label.setText(_translate("Form", "Evaluate the Performance of your Fantasy Team"))
        self.CB1.setItemText(0, _translate("Form", "----SELECT TEAM----"))
        self.CB2.setItemText(0, _translate("Form", "----SELECT MATCH----"))
        self.Label_Players.setText(_translate("Form", "PLAYERS: "))
        self.Label_Points.setText(_translate("Form", "POINTS"))
        self.Calculate_btn.setText(_translate("Form", "CALCULATE POINTS"))
        #self.lineEdit.setText(_translate("FORM", "00"))      

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
