# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fantasyCricketGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QLabel
from PyQt5.QtGui import QPixmap

from evaluteTeam2 import Ui_Form
from showTeam import Ui_showTeamWindow
from evaluteTeam2 import Ui_Form
import sqlite3

class Ui_MainWindow(object):
    def __init__(self):
        self.batCount = 0
        self.bowlCount = 0
        self.ARCount = 0
        self.WKCount = 0
        self.pointsAvailable = 1000
        self.pointsUsed = 0
        self.player_list = []

    def showTeam(self):
        #print("showTeam")
        self.Swindow = QtWidgets.QMainWindow()
        self.ui = Ui_showTeamWindow()
        self.ui.setupUi(self.Swindow)
        self.Swindow.show()
            
    def evaluateTeam(self):
        #self.createTeam()
        self.form = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.form)
        self.form.show()
        #ret = Form.exec()
        
    def databaseConn(self):
        conn = sqlite3.connect("C:\\Users\\gpavi\\Desktop\\FantasyCricketGame\\Database\\Fantasy Cricket.db")
        sqlcursor= conn.cursor()
        return sqlcursor   

    def msgbox(self,title,message,icon):
        msg= QMessageBox()
        msg.setStyleSheet("Font-size:15px; font-weight: bold;")
        msg.setWindowTitle(title)
        msg.setIconPixmap(QPixmap(icon).scaled(60,60))
        #msg.setIconSize(QSize(20,20))
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msg.setText(message)
        msg.exec_()
     
    def createTeam(self):
        self.LE_teamName.setEnabled(True)
        self.msgbox("Create New Team","Enter your team name and form a team!","Images of Fantasy Cricket\\selectTeam.jpg")
        self.RB_bat.setEnabled(True)
        self.listWidget.setEnabled(True)
        self.listWidget_2.setEnabled(True)
        self.RB_bat.setEnabled(True)
        self.RB_bowl.setEnabled(True)
        self.RB_allRounder.setEnabled(True)
        self.RB_wicketKeeper.setEnabled(True)
       # self.RB_bat.setChecked(True)
        self.LE_batsman.setText(str(self.batCount))
        self.LE_bowler.setText(str(self.bowlCount))
        self.LE_allRounder.setText(str(self.ARCount))
        self.LE_wicketKeeper.setText(str(self.WKCount))
        self.LE_pointsAvailable.setText(str(self.pointsAvailable))
        self.LE_pointsUsed.setText(str(self.pointsUsed))

    def insert(self,teamName,list_item,value):
        conn = sqlite3.connect("C:\\Users\\gpavi\\Desktop\\FantasyCricketGame\\Database\\Fantasy Cricket.db")
        
        try:
            sqlC= conn.cursor()
            sqlC.execute("INSERT INTO Teams(Tname,Players,Value) VALUES(?,?,?);",(teamName,list_item,value,))
            conn.commit()    
        except:
            #print("Error in operation")
            conn.rollback()
        conn.close()
        
    def saveTeam(self):
        sqlC = self.databaseConn()
        teamName = self.LE_teamName.text()
        list_item=[]
        teamList = []
        sqlC.execute("SELECT Tname FROM Teams")
        allTeam = sqlC.fetchall()
        
        for i in range(self.listWidget_2.count()):
                list_item.append(self.listWidget_2.item(i).text())
                
        if self.LE_teamName.text() == "":
            self.msgbox("WARNING","Team name can't be empty","Images of Fantasy Cricket\\warning.png")
        else:
            for i in allTeam:
                teamList.append(i[0])

            if teamName not in teamList:     
                if self.listWidget_2.count() == 11:
                    for i in range(len(list_item)):
                        sqlC.execute("SELECT Value FROM Stats WHERE Players = ?",(list_item[i],))
                        value = sqlC.fetchone()[0]
                
                        self.insert(teamName,list_item[i],value)
                    self.msgbox("TEAM SAVED","Hurray,your team is successfully created!","Images of Fantasy Cricket\\team2.jpg")
                    self.batCount = 0
                    self.bowlCount = 0
                    self.ARCount = 0
                    self.WKCount = 0
                    self.pointsAvailable = 1000
                    self.pointsUsed = 0

                    self.LE_batsman.setText(str(self.batCount))
                    self.LE_bowler.setText(str(self.bowlCount))
                    self.LE_allRounder.setText(str(self.WKCount))
                    self.LE_wicketKeeper.setText(str(self.ARCount))
                    self.LE_pointsAvailable.setText(str(self.pointsAvailable))
                    self.LE_pointsUsed.setText(str(self.pointsUsed))
                    self.LE_teamName.clear()
                    self.listWidget.clear()
                    self.listWidget_2.clear()                    
                else:
                    self.msgbox("WARNING","A team must contain 11 players!","Images of Fantasy Cricket\\eleven.jpg")
            else:
                self.msgbox("WARNING","Team name already exists, try other name!","Images of Fantasy Cricket\\oops.jpg")


    def bat(self):
        if self.RB_bat.isChecked():
            self.listWidget.clear()
            cursor= self.databaseConn()
            cursor.execute('SELECT Players FROM Stats WHERE Ctg == "BAT"')
            batsmen = cursor.fetchall()
            for i in batsmen:
                self.listWidget.addItem(i[0])

    def bowl(self):
        if self.RB_bowl.isChecked():
            self.listWidget.clear()
            cursor= self.databaseConn()
            cursor.execute('SELECT Players FROM Stats WHERE Ctg == "BWL"')
            bowler = cursor.fetchall()
            for i in bowler:
                self.listWidget.addItem(i[0])

    def allRounder(self):
        if self.RB_allRounder.isChecked():
            self.listWidget.clear()
            cursor= self.databaseConn()
            cursor.execute('SELECT Players FROM Stats WHERE Ctg == "AR"')
            aRounder = cursor.fetchall()
            for i in aRounder:
                self.listWidget.addItem(i[0])
                
    def wicketKeeper(self):
        if self.RB_wicketKeeper.isChecked():
            self.listWidget.clear()
            cursor= self.databaseConn()
            cursor.execute('SELECT Players FROM Stats WHERE Ctg == "WK"')
            wKeeper = cursor.fetchall()
            for i in wKeeper:
                self.listWidget.addItem(i[0])

    def updatePointsIncrement(self,item):
        sqlC = self.databaseConn()
        p = item.text()
        sqlC.execute("SELECT Value FROM stats WHERE Players = ?",(p,))
        value = sqlC.fetchone()

        self.pointsAvailable = self.pointsAvailable - value[0]
        self.pointsUsed = self.pointsUsed + value[0]
        self.LE_pointsAvailable.setText(str(self.pointsAvailable))   
        self.LE_pointsUsed.setText(str(self.pointsUsed))

    def updatePointsdecrement(self,item):
        sqlC = self.databaseConn()
        p = item.text()
        sqlC.execute("SELECT Value FROM stats WHERE Players = ?",(p,))
        value = sqlC.fetchone()
            
        self.pointsAvailable = self.pointsAvailable + value[0]
        self.LE_pointsAvailable.setText(str(self.pointsAvailable))
        self.pointsUsed = self.pointsUsed - value[0]        
        self.LE_pointsUsed.setText(str(self.pointsUsed))

    def render(self,player):
        if player in self.player_list:
            pass
        else:
            self.player_list.append(player)
        return (player_list)
        
    def removeList1(self,item):
        sqlC = self.databaseConn()
        sqlC.execute("SELECT Value FROM stats WHERE Players = ?",(item.text(),))
        value = sqlC.fetchone()
        player = []
        if (self.RB_bat.isChecked()):
            if self.batCount < 4:
                if self.pointsAvailable > value[0]:
                    playerSelected = self.listWidget.takeItem(self.listWidget.row(item))
                    for i in range(self.listWidget_2.count()):
                        player.append(self.listWidget_2.item(i).text())
                    if playerSelected.text() in player:
                        self.msgbox("ERROR","Player already selected, choose other!","Images of Fantasy Cricket\\same.png")
                    else:
                        self.listWidget_2.addItem(playerSelected.text())
                        self.batCount = self.batCount + 1
                        self.LE_batsman.setText(str(self.batCount))
                        self.updatePointsIncrement(item)            
                else:
                    self.msgbox("ERROR","Have no enough points!","Images of Fantasy Cricket\\wallet.jpg")
            else:
                self.msgbox("ERROR","Team can have only 4 Batsmen","Images of Fantasy Cricket\\warning.png")

                
        elif(self.RB_bowl.isChecked()):
            if self.bowlCount < 3:
                if self.pointsAvailable > value[0]:
                    playerSelected = self.listWidget.takeItem(self.listWidget.row(item))
                    for i in range(self.listWidget_2.count()):
                        player.append(self.listWidget_2.item(i).text())
                    if playerSelected.text() in player:
                        self.msgbox("ERROR","Player already selected, choose other!","Images of Fantasy Cricket\\same.png")
                    else:
                        self.listWidget_2.addItem(item.text())
                        self.bowlCount = self.bowlCount + 1
                        self.LE_bowler.setText(str(self.bowlCount))
                        self.updatePointsIncrement(item)
                else:
                    self.msgbox("ERROR","Have no enough points!","Images of Fantasy Cricket\\wallet.jpg")
            else:
                self.msgbox("ERROR","Team can have only 3 Bowler","Images of Fantasy Cricket\\warning.png")
                
        elif(self.RB_allRounder.isChecked()):
            if self.ARCount < 3:
                if self.pointsAvailable > value[0]:
                    playerSelected = self.listWidget.takeItem(self.listWidget.row(item))
                    for i in range(self.listWidget_2.count()):
                        player.append(self.listWidget_2.item(i).text())
                    if playerSelected.text() in player:
                        self.msgbox("ERROR","Player already selected, choose other!","Images of Fantasy Cricket\\same.png")
                    else:
                        self.listWidget_2.addItem(item.text())
                        self.ARCount = self.ARCount + 1
                        self.LE_allRounder.setText(str(self.ARCount))
                        self.updatePointsIncrement(item)
                else:
                    self.msgbox("ERROR","Have no enough points!","Images of Fantasy Cricket\\wallet.jpg")
            else:
                self.msgbox("ERROR","Team can have only 3 All-Rounder","Images of Fantasy Cricket\\warning.png")
                
        elif(self.RB_wicketKeeper.isChecked()):
            if self.pointsAvailable > value[0]:
                    if self.WKCount != 1 or self.WKCount<1:
                        playerSelected = self.listWidget.takeItem(self.listWidget.row(item))
                        for i in range(self.listWidget_2.count()):
                            player.append(self.listWidget_2.item(i).text())
                        if playerSelected.text() in player:
                            self.msgbox("ERROR","Player already selected, choose other!","Images of Fantasy Cricket\\same.png")
                        else:
                            self.listWidget_2.addItem(item.text())
                            self.WKCount = self.WKCount + 1
                            self.LE_wicketKeeper.setText(str(self.WKCount))
                            self.updatePointsIncrement(item)
                    else:
                        self.msgbox("ERROR","There can be only 1 wicket-keeper in a team","Images of Fantasy Cricket\\warning.png")
                
            else:
                self.msgbox("ERROR","Have no enough points, choose other player!","Images of Fantasy Cricket\\wallet.jpg")
                    

        
    def removeList2(self,item):
        player_L1 = []
        sqlC = self.databaseConn()
        sqlC.execute("SELECT Ctg FROM Stats WHERE Players = ?",(item.text(),))
        ctg = sqlC.fetchall()
        print(ctg)
    
            
        if ctg[0][0] == 'BAT' and self.batCount > 0:
            self.RB_bat.setChecked(True)
            player_L2 = self.listWidget_2.takeItem(self.listWidget_2.row(item))
            
            for i in range(self.listWidget.count()):
                player_L1.append(self.listWidget.item(i).text())
            if player_L2.text() in player_L1:
                pass
            else:
                self.listWidget.addItem(player_L2.text())
                
            self.batCount = self.batCount - 1
            self.LE_batsman.setText(str(self.batCount))
            self.updatePointsdecrement(item)
   
        elif ctg[0][0] == 'BWL' and self.bowlCount > 0:
            self.RB_bowl.setChecked(True)
            player_L2=self.listWidget_2.takeItem(self.listWidget_2.row(item))

            for i in range(self.listWidget.count()):
                player_L1.append(self.listWidget.item(i).text())
            if player_L2.text() in player_L1:
                pass
            else:
                self.listWidget.addItem(player_L2.text())
                
            self.bowlCount = self.bowlCount - 1
            self.LE_bowler.setText(str(self.bowlCount))
            self.updatePointsdecrement(item)
    
        elif ctg[0][0] == 'AR' and self.ARCount > 0:
            self.RB_allRounder.setChecked(True)
            player_L2=self.listWidget_2.takeItem(self.listWidget_2.row(item))
            
            for i in range(self.listWidget.count()):
                player_L1.append(self.listWidget.item(i).text())
            if player_L2.text() in player_L1:
                pass
            else:
                self.listWidget.addItem(player_L2.text())
                    
            self.ARCount = self.ARCount - 1
            self.LE_allRounder.setText(str(self.ARCount))
            self.updatePointsdecrement(item)
            
        elif ctg[0][0] == 'WK' and self.WKCount > 0:
            self.RB_wicketKeeper.setChecked(True)
            player_L2 = self.listWidget_2.takeItem(self.listWidget_2.row(item))
            
            for i in range(self.listWidget.count()):
                player_L1.append(self.listWidget.item(i).text())
            if player_L2.text() in player_L1:
                pass
            else:
                self.listWidget.addItem(player_L2.text())
                
            self.WKCount = self.WKCount - 1
            self.LE_wicketKeeper.setText(str(self.WKCount))
            self.updatePointsdecrement(item)
            
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.L1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.L1.setFont(font)
        self.L1.setObjectName("L1")
        self.verticalLayout.addWidget(self.L1)
        
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.L2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.L2.setFont(font)
        self.L2.setObjectName("L2")
        self.horizontalLayout.addWidget(self.L2)
        
        self.LE_batsman = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_batsman.setEnabled(False)
        self.LE_batsman.setStyleSheet("background-color:white; font: bold 10pt Comic Sans MS")
        self.LE_batsman.setObjectName("LE_batsman")
        #self.LE_batsman.setText(str(self.batCount))
        self.horizontalLayout.addWidget(self.LE_batsman)
        
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        
        self.L3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.L3.setFont(font)
        self.L3.setObjectName("L3")
        self.horizontalLayout.addWidget(self.L3)
        
        self.LE_bowler = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_bowler.setEnabled(False)
        self.LE_bowler.setStyleSheet("background-color:white; font: bold 10pt Comic Sans MS")
        self.LE_bowler.setObjectName("LE_bowler")
        #self.LE_bowler.setText(str(self.bowlCount))
        self.horizontalLayout.addWidget(self.LE_bowler)
        
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        
        self.L4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.L4.setFont(font)
        self.L4.setObjectName("L4")
        self.horizontalLayout.addWidget(self.L4)
        
        self.LE_allRounder = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_allRounder.setEnabled(False)
        self.LE_allRounder.setStyleSheet("background-color:white; font: bold 10pt Comic Sans MS")
        self.LE_allRounder.setObjectName("LE_allRounder")
        #self.LE_allRounder.setText(str(self.ARCount))
        self.horizontalLayout.addWidget(self.LE_allRounder)
        
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        
        self.L5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.L5.setFont(font)
        self.L5.setObjectName("L5")
        self.horizontalLayout.addWidget(self.L5)
        
        self.LE_wicketKeeper = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_wicketKeeper.setEnabled(False)
        self.LE_wicketKeeper.setStyleSheet("background-color:white; font: bold 10pt Comic Sans MS")
        self.LE_wicketKeeper.setObjectName("LE_wicketKeeper")
        #self.LE_wicketKeeper.setText(str(self.WKCount))
        
        self.horizontalLayout.addWidget(self.LE_wicketKeeper)
        self.verticalLayout.addLayout(self.horizontalLayout)
        
        spacerItem3 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        
        self.verticalLayout_5.addLayout(self.verticalLayout)
        
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        self.L6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.L6.setFont(font)
        self.L6.setObjectName("L6")
        self.horizontalLayout_2.addWidget(self.L6)
        
        self.LE_pointsAvailable = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_pointsAvailable.setEnabled(False)
        self.LE_pointsAvailable.setStyleSheet("background-color:white; font: bold 10pt Comic Sans MS")
        self.LE_pointsAvailable.setObjectName("LE_pointsAvailable")
        #self.LE_pointsAvailable.setText(str(self.pointsAvailable))
        self.horizontalLayout_2.addWidget(self.LE_pointsAvailable)
        
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        
        self.L7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.L7.setFont(font)
        self.L7.setObjectName("L7")
        self.horizontalLayout_2.addWidget(self.L7)
        
        self.LE_pointsUsed = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_pointsUsed.setEnabled(False)
        self.LE_pointsUsed.setStyleSheet("background-color:white; font: bold 10pt Comic Sans MS")
        self.LE_pointsUsed.setObjectName("LE_pointsUsed")
        #self.LE_pointsUsed.setText(str(self.pointsUsed))
        self.horizontalLayout_2.addWidget(self.LE_pointsUsed)
        
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(331, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem5)
        
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        
        self.RB_bat = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_bat.toggled.connect(self.bat)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.RB_bat.setFont(font)
        self.RB_bat.setObjectName("RB_bat")
        self.RB_bat.setEnabled(False)
        self.horizontalLayout_4.addWidget(self.RB_bat)
        
        self.RB_bowl = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_bowl.toggled.connect(self.bowl)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.RB_bowl.setFont(font)
        self.RB_bowl.setObjectName("RB_bowl")
        self.RB_bowl.setEnabled(False)
        self.horizontalLayout_4.addWidget(self.RB_bowl)
        
        self.RB_allRounder = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_allRounder.toggled.connect(self.allRounder)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.RB_allRounder.setFont(font)
        self.RB_allRounder.setObjectName("RB_allRounder")
        self.RB_allRounder.setEnabled(False)
        self.horizontalLayout_4.addWidget(self.RB_allRounder)
        
        self.RB_wicketKeeper = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_wicketKeeper.toggled.connect(self.wicketKeeper)
        
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        
        self.RB_wicketKeeper.setFont(font)
        self.RB_wicketKeeper.setObjectName("RB_wicketKeeper")
        self.RB_wicketKeeper.setEnabled(False)
        self.horizontalLayout_4.addWidget(self.RB_wicketKeeper)
        
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setEnabled(False)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.itemDoubleClicked.connect(self.removeList1)
        self.verticalLayout_2.addWidget(self.listWidget)
        
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        
        spacerItem6 = QtWidgets.QSpacerItem(17, 378, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        
        spacerItem7 = QtWidgets.QSpacerItem(17, 378, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        
        self.L8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.L8.setFont(font)
        self.L8.setObjectName("L8")
        self.horizontalLayout_5.addWidget(self.L8)
        
        self.LE_teamName = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_teamName.setEnabled(False)
        self.LE_teamName.setStyleSheet("background-color:white; font: bold 10pt Comic Sans MS")
        self.LE_teamName.setObjectName("LE_teamName")
        self.horizontalLayout_5.addWidget(self.LE_teamName)
        
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setEnabled(False)
        self.listWidget_2.setObjectName("listWidget_2")
        self.listWidget_2.itemDoubleClicked.connect(self.removeList2)
        
        self.verticalLayout_4.addWidget(self.listWidget_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        
        self.menuManage_Team = QtWidgets.QMenu(self.menubar)
        self.menuManage_Team.setObjectName("menuManage_Team")
        
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.actionNEW_Team = QtWidgets.QAction(MainWindow)
        self.actionNEW_Team.setObjectName("actionNEW_Team")
        
        self.actionOPEN_Team = QtWidgets.QAction(MainWindow)
        self.actionOPEN_Team.setObjectName("actionOPEN_Team")
        
        self.actionSAVE_Team = QtWidgets.QAction(MainWindow)
        self.actionSAVE_Team.setObjectName("actionSAVE_Team")
        
        self.actionEVALUATE_Team = QtWidgets.QAction(MainWindow)
        self.actionEVALUATE_Team.setObjectName("actionEVALUATE_Team")
        
        self.menuManage_Team.addAction(self.actionNEW_Team)
        self.menuManage_Team.addAction(self.actionOPEN_Team)
        self.menuManage_Team.addAction(self.actionSAVE_Team)
        self.menuManage_Team.addAction(self.actionEVALUATE_Team)
        self.menubar.addAction(self.menuManage_Team.menuAction())

        self.actionNEW_Team.triggered.connect(self.createTeam)
        self.actionSAVE_Team.triggered.connect(self.saveTeam)
        self.actionEVALUATE_Team.triggered.connect(self.evaluateTeam)
        self.actionOPEN_Team.triggered.connect(self.showTeam)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

                
    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FANTASY CRICKET TEAM"))
        self.L1.setText(_translate("MainWindow", "  Your Selection"))
        self.L2.setText(_translate("MainWindow", "Batsman(BAT)"))
        self.L3.setText(_translate("MainWindow", "Bowlers(BOW)"))
        self.L4.setText(_translate("MainWindow", "Allrounders(AR)"))
        self.L5.setText(_translate("MainWindow", "Wicket-keeper(WR)"))
        self.L6.setText(_translate("MainWindow", "Points Available : "))
        self.L7.setText(_translate("MainWindow", "Points Used : "))
        
        self.RB_bat.setText(_translate("MainWindow", "BAT"))
        self.RB_bowl.setText(_translate("MainWindow", "BOWL"))
        self.RB_allRounder.setText(_translate("MainWindow", "AR"))
        self.RB_wicketKeeper.setText(_translate("MainWindow", "WK"))
        
        self.label_9.setText(_translate("MainWindow", " >"))
        self.L8.setText(_translate("MainWindow", "Team Name "))

        self.LE_batsman.setPlaceholderText(_translate("MainWindow", u"##", None))
        self.LE_bowler.setPlaceholderText(_translate("MainWindow", u"##", None))
        self.LE_allRounder.setPlaceholderText(_translate("MainWindow", u"##", None))
        self.LE_wicketKeeper.setPlaceholderText(_translate("MainWindow", u"##", None))
        self.LE_pointsAvailable.setPlaceholderText(_translate("MainWindow", u"##", None))
        self.LE_pointsUsed.setPlaceholderText(_translate("MainWindow", u"##", None))
        
        self.menuManage_Team.setTitle(_translate("MainWindow", "Manage Team"))
        self.actionNEW_Team.setText(_translate("MainWindow", "NEW Team"))
        self.actionOPEN_Team.setText(_translate("MainWindow", "OPEN Team"))
        self.actionSAVE_Team.setText(_translate("MainWindow", "SAVE Team"))
        self.actionEVALUATE_Team.setText(_translate("MainWindow", "EVALUATE Team"))

        
         
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
