# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showTeamGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from openTeam import Ui_openTeamWindow
#from fantasyCricket2 import Ui_MainWindow

class Ui_showTeamWindow(object):
    def databaseConn(self):
        conn = sqlite3.connect("C:\\Users\\gpavi\\Desktop\\FantasyCricketGame\\Database\\Fantasy Cricket.db")
        sqlcursor= conn.cursor()
        return sqlcursor

    def show(self):
        sqlC = self.databaseConn()
        sqlC.execute("SELECT DISTINCT Tname FROM Teams")
        teams = sqlC.fetchall()
        for i in teams:
            self.comboBox.addItem(i[0])
            
    def open_team(self):
        #players = []
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_openTeamWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        team = self.comboBox.currentText()
     
        self.ui.lineEdit_teamName.setText(team)
        self.ui.list2()

    def setupUi(self, showTeamWindow):
        showTeamWindow.setObjectName("showTeamWindow")
        showTeamWindow.resize(306, 190)
        showTeamWindow.setStyleSheet("padding: 0px")
        self.centralwidget = QtWidgets.QWidget(showTeamWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Label = QtWidgets.QLabel(self.centralwidget)
        self.Label.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Label.setFont(font)
        self.Label.setStyleSheet("padding:0px")
        self.Label.setScaledContents(False)
        self.Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Label.setWordWrap(False)
        self.Label.setObjectName("Label")
        self.verticalLayout_5.addWidget(self.Label)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setStyleSheet("height:20px")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_5.addWidget(self.comboBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cancel_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_4.addWidget(self.cancel_btn)
        self.ok_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ok_btn.setFont(font)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout_4.addWidget(self.ok_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        showTeamWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(showTeamWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 306, 21))
        self.menubar.setObjectName("menubar")
        showTeamWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(showTeamWindow)
        self.statusbar.setObjectName("statusbar")
        showTeamWindow.setStatusBar(self.statusbar)

        self.show()
        self.ok_btn.clicked.connect(self.open_team)
                
        self.retranslateUi(showTeamWindow)
        QtCore.QMetaObject.connectSlotsByName(showTeamWindow)

    def retranslateUi(self, showTeamWindow):
        _translate = QtCore.QCoreApplication.translate
        showTeamWindow.setWindowTitle(_translate("showTeamWindow", "Show Team"))
        self.Label.setText(_translate("showTeamWindow", " CHOOSE TEAM"))
        self.cancel_btn.setText(_translate("showTeamWindow", "Cancel"))
        self.ok_btn.setText(_translate("showTeamWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    showTeamWindow = QtWidgets.QMainWindow()
    ui = Ui_showTeamWindow()
    ui.setupUi(showTeamWindow)
    showTeamWindow.show()
    sys.exit(app.exec_())
